# Konfigurasi default
security:
  jwt:
    token:
      secret-key: my-secret-key
      expiryMillis: 3600000
app:
  verify:
    email-verification: true
    client: http://localhost:8080/api/users/confirm?token=
    register-expiry: 10
spring:
  application:
    name: BackendServiceApplication
  config:
    import: application-profiles.yml
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
pdf:
  storage:
    base-path: C:/Users/yalexius/Documents/YOGI/pdf-storage
server:
  port: 8081
